name: Test security-insecure in GitHub actions, with docker/setup-buildx-action using defaults and configuration

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  DOCKER_BUILDKIT: '1'

defaults:
  run:
    shell: bash

jobs:

  test:
    strategy:
      matrix:
        set-config: [ "default", "flags", "toml", "inline" ]
        dockerfile: [ "Dockerfile", "Dockerfile.security" ]
      fail-fast: false
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      -
        if: matrix.set-config == 'toml'
        name: Create buildkitd config override
        run: |
          echo "experimantal = true" > /tmp/buildkitd.toml
          echo "debug = true" > /tmp/buildkitd.toml
          echo 'insecure-entitlements = [ "security.insecure" ]' >> /tmp/buildkitd.toml
          cat /tmp/buildkitd.toml
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        if: matrix.set-config == 'flags'
        name: Set up Docker Buildx with buildkit flags
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug --allow-insecure-entitlement security.insecure
      -
        if: matrix.set-config == 'inline'
        name: Set up Docker Buildx with inline buildkit config
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
          config-inline: |
            debug = true
            experimental = true
            insecure-entitlements = [ "security.insecure" ]
      -
        if: matrix.set-config == 'toml'
        name: Set up Docker Buildx with custom buildkit toml config
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
          config: /tmp/buildkitd.toml
      -
        if: matrix.set-config == 'default'
        name: Set up Docker Buildx with defaults
        uses: docker/setup-buildx-action@v2
#        with:
#           Cannot set debug this way, it overrides the defaults
#           buildkitd-flags: --debug
      -
        name: Build for armv7
        uses: docker/build-push-action@v3
        with:
          file: ${{ matrix.dockerfile }}
          platforms: "linux/arm/v7"
          push: false
          allow: |
            security.insecure
      -
        name: Build and load on host arch
        uses: docker/build-push-action@v3
        with:
          file: ${{ matrix.dockerfile }}
          tags: test-image:latest
          load: true
          push: false
          allow: |
            security.insecure
      -
        name: Test image
        uses: addnab/docker-run-action@v3
        with:
          image: test-image:latest
          run: /demo/test.sh
